/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.bugManage.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.bugManage.entity.Bug;

/** 
 * MyEclipse Struts
 * Creation date: 02-23-2012
 * 
 * XDoclet definition:
 * @struts.form name="bugForm"
 */
public class BugForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** bug property */
	private Bug bug=new Bug();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the bug.
	 * @return Bug
	 */
	public Bug getBug() {
		return bug;
	}

	/** 
	 * Set the bug.
	 * @param bug The bug to set
	 */
	public void setBug(Bug bug) {
		this.bug = bug;
	}
}