/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.bugManage.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.bugManage.entity.Projectmodel;

/** 
 * MyEclipse Struts
 * Creation date: 02-25-2012
 * 
 * XDoclet definition:
 * @struts.form name="modelForm"
 */
public class ModelForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private Projectmodel model = new Projectmodel();
	private String promodelname;
	private String fathermodelname;
	

	public String getPromodelname() {
		return promodelname;
	}

	public void setPromodelname(String promodelname) {
		this.promodelname = promodelname;
	}

	public String getFathermodelname() {
		return fathermodelname;
	}

	public void setFathermodelname(String fathermodelname) {
		this.fathermodelname = fathermodelname;
	}

	public Projectmodel getModel() {
		return model;
	}

	public void setModel(Projectmodel model) {
		this.model = model;
	}
	
	
}