/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.bugManage.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.bugManage.entity.Project;
import org.bugManage.format.dateFormat;

/** 
 * MyEclipse Struts
 * Creation date: 02-22-2012
 * 
 * XDoclet definition:
 * @struts.form name="projectForm"
 */
public class ProjectForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	
	private Project project = new Project();
	private dateFormat format = new dateFormat();
	private String startTime;
	private String endTime;
	
	

	public void setFormat(dateFormat format) {
		this.format = format;
	}

	public String getStartTime() {
		
		return this.format.dateToString(this.project.getStarttime());
	}

	public void setStartTime(String startTime) {
		this.getProject().setStarttime(this.format.stringToDate(startTime));
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.format.dateToString(this.project.getForefinishtime());
	}

	public void setEndTime(String endTime) {
		this.getProject().setForefinishtime(this.format.stringToDate(endTime));
		this.endTime = endTime;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}
	
	
	
}